### ISSUE TITLE
Runtime error on setVariableOnTFC

### ISSUE THREAD

**Issue by razaj92** [mvisonneau/tfcw#23]
Seeing the following while applying a render on tfc

```
INFO[2020-04-08T11:40:27+01:00] Processing variables and updating their values on TFC
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17d5be8]

goroutine 114 [running]:
github.com/mvisonneau/tfcw/lib/client.(*Client).setVariableOnTFC(0xc00064a1e0, 0xc0002446c0, 0xc0003b4540, 0xc0008cca20, 0xc000470d20, 0x0, 0xc0000b7500, 0xc000601f70)
	/Users/rjhaveri/Github/RazaJ92/tfcw/lib/client/variables.go:48 +0x658
github.com/mvisonneau/tfcw/lib/client.(*Client).renderVariableOnTFC(0xc00064a1e0, 0xc0002446c0, 0xc0003b4540, 0xc0008cca20, 0xc000470d20, 0xc0008ee000, 0x0, 0x1)
	/Users/rjhaveri/Github/RazaJ92/tfcw/lib/client/variables.go:310 +0xaa
github.com/mvisonneau/tfcw/lib/client.(*Client).renderVariablesOnTFC.func2(0xc0000b7500, 0xc0005472a0, 0xc0000b75c0, 0xc00064a1e0, 0xc0002446c0, 0xc0003b4540, 0xc000470d20, 0x0, 0xc00046ee10)
	/Users/rjhaveri/Github/RazaJ92/tfcw/lib/client/variables.go:201 +0x79
created by github.com/mvisonneau/tfcw/lib/client.(*Client).renderVariablesOnTFC
	/Users/rjhaveri/Github/RazaJ92/tfcw/lib/client/variables.go:198 +0x293
```

**Comment by mvisonneau** [comment]
indeed, sorry about that, I need to workout the test suite a bit more.. should be sorted in the next release :)
